# default.yaml

# 默认支持的ROS消息类型：
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (如果需要更多，请在ros_sub_pub.hpp中修改/添加)

# 支持的最大send_topics数量：50

# 列出所有<IPname: IP>的映射（IPname可以任意设置）
IP:
  self: '*'   # '*' 表示所有本机IP
  robot1: 192.168.1.101    # 机器人1的IP
  robot2: 192.168.1.102    # 机器人2的IP
  test_local: 127.0.0.1    # 仅用于本地机器测试

# 发送这些ROS消息到远程机器人
# 如果不需要send_topics，请注释掉以下内容
send_topics:
- topic_name: /imu          # IMU话题
  msg_type: sensor_msgs/Imu # 消息类型
  max_freq: 50              # 最大发送频率 (Hz)
  srcIP: self               # 源IP，使用IP映射中的self
  srcPort: 3001             # 源端口

- topic_name: /cmd_vel      # 速度指令话题
  msg_type: geometry_msgs/Twist
  max_freq: 40
  srcIP: self
  srcPort: 3002

- topic_name: /string       # 字符串话题
  msg_type: std_msgs/String
  max_freq: 15
  srcIP: self
  srcPort: 3003

- topic_name: /test1        # 测试话题
  msg_type: std_msgs/String
  max_freq: 20
  srcIP: self
  srcPort: 3004

# 从远程机器人接收这些ROS消息
# 如果不需要recv_topics，请注释掉以下内容
recv_topics:
- topic_name: /imu_recv     # 接收的IMU话题
  msg_type: sensor_msgs/Imu
  srcIP: test_local         # 源IP，使用本地测试地址
  srcPort: 3001             # 源端口

- topic_name: /cmd_vel_recv # 接收的速度指令话题
  msg_type: geometry_msgs/Twist
  srcIP: test_local
  srcPort: 3002

- topic_name: /string_recv  # 接收的字符串话题
  msg_type: std_msgs/String
  srcIP: test_local
  srcPort: 3003

- topic_name: /test1_recv        # 接收的测试话题
  msg_type: std_msgs/String
  srcIP: test_local
  srcPort: 3004

# 服务配置
services:
- service_name: /set_bool   # SetBool服务
  service_type: std_srvs/SetBool
  srcIP: self               # 源IP
  srcPort: 5555             # 源端口

- service_name: /get_plan   # GetPlan服务
  service_type: nav_msgs/GetPlan
  srcIP: self
  srcPort: 5556