# default.yaml

# 默认支持的ROS消息类型：
# sensor_msgs/Imu, geometry_msgs/Twist, std_msgs/String
# 服务类型：std_srvs/SetBool, nav_msgs/GetPlan
# (如需更多类型，请在ros_sub_pub.hpp中添加)

# 支持的最大send_topics数量：50

# IP映射
IP:
  self: '*'           # '*' 表示所有本机IP
  robot1: 192.168.1.101
  robot2: 192.168.1.102
  robot3: 192.168.1.103
  test_local: 127.0.0.1
# 发送话题配置
send_topics:
- topic: /imu
  message_type: sensor_msgs/Imu
  max_frequency: 50
  bind_address: self
  port: 3001
- topic: /cmd_vel
  message_type: geometry_msgs/Twist
  max_frequency: 40
  bind_address: self
  port: 3002
- topic: /string
  message_type: std_msgs/String
  max_frequency: 15
  bind_address: self
  port: 3003
- topic: /test1
  message_type: std_msgs/String
  max_frequency: 20
  bind_address: self
  port: 3004

# 接收话题配置
recv_topics:
- topic: /imu_recv
  message_type: sensor_msgs/Imu
  connect_address: test_local
  port: 3001
- topic: /cmd_vel_recv
  message_type: geometry_msgs/Twist
  connect_address: test_local
  port: 3002
- topic: /string_recv
  message_type: std_msgs/String
  connect_address: test_local
  port: 3003
- topic: /test1_recv
  message_type: std_msgs/String
  connect_address: test_local
  port: 3004

# 提供服务配置（接收请求，REP模式）
provide_services:
- service_name: /set_bool
  service_type: std_srvs/SetBool
  bind_address: self
  port: 5555
- service_name: /get_plan
  service_type: nav_msgs/GetPlan
  bind_address: self
  port: 5556

# 请求服务配置（发送请求，REQ模式）
request_services:
- service_name: /remote_set_bool
  service_type: std_srvs/SetBool
  connect_address: test_local
  port: 5555
- service_name: /remote_get_plan
  service_type: nav_msgs/GetPlan
  connect_address: test_local
  port: 5556