### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robot1: 192.168.1.101
  robot2: 192.168.1.102
  test_local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /imu
  msg_type: sensor_msgs/Imu
  max_freq: 50
  srcIP: test_local
  srcPort: 3001

- topic_name: /cmd_vel
  msg_type: geometry_msgs/Twist
  max_freq: 50
  srcIP: test_local
  srcPort: 3002

- topic_name: /string
  msg_type: std_msgs/String
  max_freq: 10
  srcIP: test_local
  srcPort: 3003

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /imu_recv
  msg_type: sensor_msgs/Imu
  srcIP: test_local
  srcPort: 3001

- topic_name: /cmd_vel_recv
  msg_type: geometry_msgs/Twist
  srcIP: test_local
  srcPort: 3002

- topic_name: /string_recv
  msg_type: std_msgs/String
  srcIP: test_local
  srcPort: 3003

####### Services #######
services:
- service_name: /set_bool
  service_type: std_srvs/SetBool
  srcIP: self
  srcPort: 5555

- service_name: /get_plan
  service_type: nav_msgs/GetPlan
  srcIP: self
  srcPort: 5556