# Multibotnet v4.0.0 本地测试配置文件
# 
# 用于在单机上测试，所有连接都使用localhost

# IP地址映射
IP:
  self: '*'                    # '*' 表示绑定所有本机IP
  localhost: '127.0.0.1'       # 本地回环
  robot1: '127.0.0.1'          # 模拟机器人1 - 使用本地地址
  robot2: '127.0.0.1'          # 模拟机器人2 - 使用本地地址
  robot3: '127.0.0.1'          # 模拟机器人3 - 使用本地地址
  server: '127.0.0.1'          # 模拟服务器 - 使用本地地址

# 发送话题配置
send_topics:
  # IMU数据发送
  - topic: /imu
    message_type: sensor_msgs/Imu
    max_frequency: 50
    bind_address: self
    port: 3001
    compression: true
    batch: true
    batch_size: 10
    batch_timeout_ms: 50

  # 速度命令发送
  - topic: /cmd_vel
    message_type: geometry_msgs/Twist
    max_frequency: 40
    bind_address: self
    port: 3002
    compression: false

  # 激光雷达数据
  - topic: /scan
    message_type: sensor_msgs/LaserScan
    max_frequency: 10
    bind_address: self
    port: 3003
    compression: true
    batch: true
    batch_size: 5

  # 点云数据
  - topic: /velodyne_points
    message_type: sensor_msgs/PointCloud2
    max_frequency: 10
    bind_address: self
    port: 3004
    compression: true
    batch: false

  # 机器人状态（注释掉自定义消息，避免类型错误）
  # - topic: /robot_status
  #   message_type: your_package/RobotStatus
  #   max_frequency: 1
  #   bind_address: self
  #   port: 3005

# 接收话题配置 - 本地测试时注释掉，避免连接错误
recv_topics: []
  # # 接收其他机器人的IMU数据
  # - topic: /robot1/imu
  #   message_type: sensor_msgs/Imu
  #   connect_address: localhost
  #   port: 3001

  # - topic: /robot2/imu
  #   message_type: sensor_msgs/Imu
  #   connect_address: localhost
  #   port: 3001

  # # 接收中央服务器的全局命令
  # - topic: /global_cmd_vel
  #   message_type: geometry_msgs/Twist
  #   connect_address: server
  #   port: 3002

# 提供服务配置
provide_services:
  # 基础服务
  - service_name: /set_mode
    service_type: std_srvs/SetBool
    bind_address: self
    port: 5001

  # 路径规划服务
  - service_name: /get_plan
    service_type: nav_msgs/GetPlan
    bind_address: self
    port: 5002
    timeout_ms: 10000

  # 注释掉自定义服务，避免类型错误
  # - service_name: /robot_control
  #   service_type: your_package/RobotControl
  #   bind_address: self
  #   port: 5003

# 请求服务配置 - 本地测试时注释掉
request_services: []
  # # 请求其他机器人的服务
  # - service_name: /robot1/set_mode
  #   service_type: std_srvs/SetBool
  #   connect_address: robot1
  #   port: 5001
  #   timeout_ms: 5000
  #   max_retries: 3

  # # 请求中央服务器的全局路径规划
  # - service_name: /server/global_planner
  #   service_type: nav_msgs/GetPlan
  #   connect_address: server
  #   port: 5002
  #   timeout_ms: 30000
  #   max_retries: 1

# 高级配置选项
advanced:
  # 压缩配置
  compression:
    enable: true
    type: lz4
    level: 6

  # 批处理配置
  batch:
    enable: true
    size: 10
    timeout_ms: 100

  # 线程池配置
  thread_pool:
    size: 0

  # 连接池配置
  connection_pool:
    min_connections: 1
    max_connections: 10
    connection_timeout_ms: 5000
    idle_timeout_ms: 60000

  # 性能监控
  performance:
    enable_statistics: true
    statistics_interval_ms: 5000

  # 健康检查
  health_check:
    enable: true
    interval_ms: 5000

  # 重试策略
  retry:
    max_retries: 3
    interval_ms: 1000